version: "2"
linters:
  enable:
    - copyloopvar
    - durationcheck
    - makezero
    - misspell
    - nilerr
    - prealloc
    - unconvert
    - unparam
  exclusions:
    generated: lax
    paths:
      - scratch
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - scratch
      - third_party$
      - builtin$
      - examples$
