
linters:
  enable:
    - errcheck
    - staticcheck
    - govet
    - ineffassign
    - unused
    - misspell
    - gofmt
    - goimports
    - unparam
    - unconvert
    - prealloc
    - makezero
    - nilerr
    - durationcheck
    - copyloopvar

issues:
  exclude-use-default: false
  exclude-dirs:
    - scratch
