repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.61.0
    hooks:
      - id: golangci-lint
        args: ["-v"]
  - repo: local
    hooks:
      - id: goimports
        name: goimports
        language: system
        pass_filenames: false
        entry: "bash -lc \"command -v goimports >/dev/null 2>&1 && goimports -w . || { echo 'goimports not found. Install with: go install golang.org/x/tools/cmd/goimports@latest'; exit 1; }\""
        stages: [commit]
      - id: go-fmt
        name: go fmt
        language: system
        pass_filenames: false
        entry: "bash -lc 'go fmt ./...'"
        stages: [commit]
      - id: terraform-fmt-examples
        name: terraform fmt (examples)
        language: system
        pass_filenames: false
        entry: bash
        args:
          - -lc
          - command -v terraform >/dev/null 2>&1 && terraform fmt -check -recursive examples || { echo 'terraform not installed; skipping terraform fmt check for examples'; exit 0; }
        stages: [commit]
      - id: copywrite-headers
        name: copywrite headers check
        language: system
        pass_filenames: false
        entry: bash
        args:
          - -lc
          - command -v copywrite >/dev/null 2>&1 && copywrite headers --config copywrite.hcl -s MPL-2.0 -c "DevOps Wiz" --check || { echo "copywrite not installed; skipping license header check"; exit 0; }
        stages: [commit]
      - id: docs-generate-no-diff
        name: docs generation no-diff (go generate ./...)
        language: system
        pass_filenames: false
        entry: bash
        args:
          - -lc
          - go generate ./... >/dev/null 2>&1; git diff --quiet -- docs/ || { echo "Docs are out of date. Run: task gen and commit updated docs/"; git --no-pager diff -- docs/; exit 1; }
        stages: [commit]
      - id: unit-tests
        name: go test (unit)
        language: system
        pass_filenames: false
        entry: bash
        args:
          - -lc
          - TF_ACC= go test ./...
        stages: [commit]
