package provider

import (
	"context"
	"fmt"
	jira "github.com/ctreminiom/go-atlassian/v2/jira/v3"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int32planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

var _ resource.Resource = (*workTypeResource)(nil)
var _ resource.ResourceWithValidateConfig = (*workTypeResource)(nil)
var _ resource.ResourceWithConfigure = (*workTypeResource)(nil)
var _ resource.ResourceWithImportState = (*workTypeResource)(nil)

func NewWorkTypeResource() resource.Resource {
	return &workTypeResource{}
}

type workTypeResource struct {
	client  *jira.Client
	premium bool
}

func (r *workTypeResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_work_type"
}

func (r *workTypeResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	provider, ok := req.ProviderData.(*JiraProvider)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected JiraProvider, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = provider.client
	r.premium = provider.premium
}

func (r *workTypeResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	if r.premium {
		return
	}

	var data workTypeResourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	hierarchyLevel := data.HierarchyLevel.ValueInt32()

	if hierarchyLevel != 0 && hierarchyLevel != -1 {
		resp.Diagnostics.AddAttributeError(path.Root("hierarchy_level"), "Hierarchy Level", fmt.Sprintf("Hierarchy Level is not supported in Standard Jira instances. Hierarchy Level: %d", hierarchyLevel))
		return
	}

}

func (r *workTypeResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {

	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Jira work type. Issue types are used to define the structure of different types of issues or work items in your Jira client.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				MarkdownDescription: "The unique identifier of the work type. Automatically generated by Jira when the work type is created.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The display name of the work type. This appears in the issue creation dialog and issue views.",
			},
			"icon_url": schema.StringAttribute{
				MarkdownDescription: "The URL of the work type's icon.",
				Computed:            true,
			},
			"description": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "A detailed description of the work type. This helps users understand the purpose and usage of this work type.",
			},
			"subtask": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Indicates whether this work type is used for subtasks. When `true`, issues of this type can only be created as children of other issues.",
			},
			"avatar_id": schema.Int64Attribute{
				Computed:            true,
				MarkdownDescription: "The ID of the avatar for the work type.",
			},
			"hierarchy_level": schema.Int32Attribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.Int32{
					int32planmodifier.RequiresReplaceIfConfigured(),
				},
				MarkdownDescription: hierarchyDescription,
			},
		},
	}
}

func (r *workTypeResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	CreateResource(ctx, req, resp, &workTypeResourceModel{}, r.client.Issue.Type.Create)
}

func (r *workTypeResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	ReadResource(ctx, req, resp, &workTypeResourceModel{}, r.client.Issue.Type.Get)
}

func (r *workTypeResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	UpdateResource(ctx, req, resp, &workTypeResourceModel{}, r.client.Issue.Type.Update)
}

func (r *workTypeResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	DeleteResource(ctx, req, resp, &workTypeResourceModel{}, r.client.Issue.Type.Delete)
}

func (r *workTypeResource) ImportState(ctx context.Context, request resource.ImportStateRequest, response *resource.ImportStateResponse) {
	ImportResource(ctx, request, response, &workTypeResourceModel{}, r.client.Issue.Type.Get)
}
