// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/ctreminiom/go-atlassian/v2/pkg/infra/models"
	"github.com/ctreminiom/go-atlassian/v2/service/jira"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int32planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

var _ resource.Resource = (*workTypeResource)(nil)
var _ resource.ResourceWithValidateConfig = (*workTypeResource)(nil)
var _ resource.ResourceWithConfigure = (*workTypeResource)(nil)
var _ resource.ResourceWithImportState = (*workTypeResource)(nil)

// NewWorkTypeResource returns the Terraform resource implementation for jira_work_type.
func NewWorkTypeResource() resource.Resource {
	return &workTypeResource{}
}

type workTypeResource struct {
	ServiceClient
	typeService jira.TypeConnector
	crudRunner  CRUDRunner[workTypeResourceModel, *models.IssueTypePayloadScheme, *models.IssueTypeScheme]
}

func (r *workTypeResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_work_type"
}

func (r *workTypeResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	provider, ok := req.ProviderData.(*JiraProvider)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected JiraProvider, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = provider.client
	r.typeService = provider.client.Issue.Type
	r.providerTimeouts = provider.providerTimeouts
}

func (r *workTypeResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data workTypeResourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	hierarchyLevel := data.HierarchyLevel.ValueInt32()
	if hierarchyLevel != 0 && hierarchyLevel != -1 {
		resp.Diagnostics.AddAttributeError(
			path.Root("hierarchy_level"),
			"Hierarchy Level",
			fmt.Sprintf(
				"Hierarchy Level %d is not supported on Standard Jira. Allowed values on Standard: -1 (sub-task) or 0 (standard). Levels >= 1 (for example, 1 = Epic) require Jira Software Premium (Advanced Roadmaps). See Atlassian documentation: Issue type hierarchy: https://support.atlassian.com/jira-software-cloud/docs/issue-type-hierarchy/ and Configure issue type hierarchy: https://support.atlassian.com/jira-software-cloud/docs/configure-issue-type-hierarchy/. If you are on Premium, manage hierarchy levels in Jira admin and omit hierarchy_level in Terraform.",
				int(hierarchyLevel),
			),
		)
		return
	}
}

func (r *workTypeResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {

	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Jira work type. Issue types are used to define the structure of different types of issues or work items in your Jira client.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				MarkdownDescription: "The unique identifier of the work type. Automatically generated by Jira when the work type is created.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The display name of the work type. This appears in the issue creation dialog and issue views.",
			},
			"icon_url": schema.StringAttribute{
				MarkdownDescription: "The URL of the work type's icon.",
				Computed:            true,
			},
			"description": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "A detailed description of the work type. This helps users understand the purpose and usage of this work type.",
			},
			"subtask": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Indicates whether this work type is used for subtasks. When `true`, issues of this type can only be created as children of other issues.",
			},
			"avatar_id": schema.Int64Attribute{
				Computed:            true,
				MarkdownDescription: "The ID of the avatar for the work type.",
			},
			"hierarchy_level": schema.Int32Attribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.Int32{
					int32planmodifier.RequiresReplaceIfConfigured(),
				},
				MarkdownDescription: HierarchyDescription,
			},
		},
	}
}

func (r *workTypeResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	ctx, cancel := withTimeout(ctx, r.providerTimeouts.Create)
	defer cancel()

	diags := r.crudRunner.DoCreate(
		ctx,
		func(ctx context.Context, dst *workTypeResourceModel) diag.Diagnostics {
			return req.Plan.Get(ctx, dst)
		},
		func(ctx context.Context, src *workTypeResourceModel) diag.Diagnostics {
			return resp.State.Set(ctx, src)
		},
		ensureWith(&resp.Diagnostics),
	)
	resp.Diagnostics.Append(diags...)
}

func (r *workTypeResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	ctx, cancel := withTimeout(ctx, r.providerTimeouts.Read)
	defer cancel()

	diags := r.crudRunner.DoRead(
		ctx,
		func(ctx context.Context, dst *workTypeResourceModel) diag.Diagnostics {
			return req.State.Get(ctx, dst)
		},
		func(ctx context.Context, src *workTypeResourceModel) diag.Diagnostics {
			return resp.State.Set(ctx, src)
		},
		func(ctx context.Context) { resp.State.RemoveResource(ctx) },
		ensureWith(&resp.Diagnostics),
		HTTPStatusFromScheme,
	)
	resp.Diagnostics.Append(diags...)
}

func (r *workTypeResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	ctx, cancel := withTimeout(ctx, r.providerTimeouts.Update)
	defer cancel()

	diags := r.crudRunner.DoUpdate(
		ctx,
		func(ctx context.Context, dst *workTypeResourceModel) diag.Diagnostics {
			return req.Plan.Get(ctx, dst)
		},
		func(ctx context.Context, src *workTypeResourceModel) diag.Diagnostics {
			return resp.State.Set(ctx, src)
		},
		ensureWith(&resp.Diagnostics),
	)
	resp.Diagnostics.Append(diags...)
}

func (r *workTypeResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	ctx, cancel := withTimeout(ctx, r.providerTimeouts.Delete)
	defer cancel()

	diags := r.crudRunner.DoDelete(
		ctx,
		func(ctx context.Context, dst *workTypeResourceModel) diag.Diagnostics {
			return req.State.Get(ctx, dst)
		},
		ensureWith(&resp.Diagnostics),
	)
	resp.Diagnostics.Append(diags...)
}

func (r *workTypeResource) ImportState(ctx context.Context, request resource.ImportStateRequest, response *resource.ImportStateResponse) {
	ctx, cancel := withTimeout(ctx, r.providerTimeouts.Read)
	defer cancel()

	diags := r.crudRunner.DoImport(
		ctx,
		request.ID,
		func(ctx context.Context, src *workTypeResourceModel) diag.Diagnostics {
			return response.State.Set(ctx, src)
		},
		ensureWith(&response.Diagnostics),
	)
	response.Diagnostics.Append(diags...)
}

// hooks returns the CRUD hooks for the generic runner.
func (r *workTypeResource) hooks() CRUDHooks[workTypeResourceModel, *models.IssueTypePayloadScheme, *models.IssueTypeScheme] {
	return CRUDHooks[workTypeResourceModel, *models.IssueTypePayloadScheme, *models.IssueTypeScheme]{
		BuildPayload: func(ctx context.Context, st *workTypeResourceModel) (*models.IssueTypePayloadScheme, diag.Diagnostics) {
			var diags diag.Diagnostics
			p := &models.IssueTypePayloadScheme{
				Name:           st.Name.ValueString(),
				Description:    st.Description.ValueString(),
				HierarchyLevel: int(st.HierarchyLevel.ValueInt32()),
			}
			return p, diags
		},
		APICreate: func(ctx context.Context, p *models.IssueTypePayloadScheme) (*models.IssueTypeScheme, *models.ResponseScheme, error) {
			return r.typeService.Create(ctx, p)
		},
		APIRead: func(ctx context.Context, id string) (*models.IssueTypeScheme, *models.ResponseScheme, error) {
			return r.typeService.Get(ctx, id)
		},
		APIUpdate: func(ctx context.Context, id string, p *models.IssueTypePayloadScheme) (*models.IssueTypeScheme, *models.ResponseScheme, error) {
			return r.typeService.Update(ctx, id, p)
		},
		APIDelete: func(ctx context.Context, id string) (*models.ResponseScheme, error) {
			return r.typeService.Delete(ctx, id)
		},
		ExtractID:               func(st *workTypeResourceModel) string { return st.ID.ValueString() },
		MapToState:              mapWorkTypeSchemeToModel,
		TreatDelete404AsSuccess: true,
	}
}

// HierarchyDescription provides details about the levels of work types in the Jira issue type hierarchy. It includes:
// - -1: Sub-task (child issue type)
// - 0: Standard issue type (default level)
// - 1: Epic (Epic level)
// Higher levels (2+) are available in Jira Software Premium with Advanced Roadmaps.
const HierarchyDescription = `
The level of the work type in the Jira issue type hierarchy:
  - -1: Sub-task (child issue type)
  - 0: Standard issue type (default level)
  - 1: Epic (Epic level)
Higher levels (2+) are available only in Jira Software Premium via Advanced Roadmaps custom hierarchy. Standard editions do not support setting levels above 0 (except -1 for sub-tasks).
References:
- Atlassian: Issue type hierarchy — https://support.atlassian.com/jira-software-cloud/docs/issue-type-hierarchy/
- Atlassian: Configure issue type hierarchy (Advanced Roadmaps) — https://support.atlassian.com/jira-software-cloud/docs/configure-issue-type-hierarchy/
`
