name: Acceptance

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: acc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  acceptance_test:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    name: Acceptance Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        terraform:
          - "1.7.*"
          - "1.8.*"
          - "1.9.*"
          - "1.10.*"
          - "1.11.*"
          - "1.12.*"
          - "1.13.*"
    steps:
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@1d76b952eb9246b03e20e15a9ef98c6d4af389ef # v5.5.0
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@97f030cf6dc0b4f5e0da352c7bca9cca34579800 # v3.1.0
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - run: go install gotest.tools/gotestsum@latest
      - run: go install github.com/bitfield/gotestdox/cmd/gotestdox@latest
      - env:
          JIRA_ENDPOINT: ${{ vars.JIRA_ENDPOINT }}
          JIRA_API_EMAIL: ${{ secrets.JIRA_API_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_TEST_ROLE_LEAD_ID: ${{ secrets.JIRA_PROJECT_TEST_ROLE_LEAD_ID }}
        run: task test ACC_ONLY=true
