

name: CI

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - ".idea"
      - ".vscode"
      - public
      - "LICENSE"
      - ".gitignore"
      - ".gitattributes"
      - ".editorconfig"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.gif"
      - "**/*.svg"
      - "**/*.ico"
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  license_headers:
    name: Verify SPDX license headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v5.5.0
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Install copywrite
        run: go install github.com/hashicorp/copywrite@latest
      - name: Check headers for Go files (SPDX MPL-2.0)
        shell: bash
        run: |
          $(go env GOPATH)/bin/copywrite headers --config copywrite.hcl -s MPL-2.0 -c "DevOps Wiz"
          git diff --exit-code

  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v5.5.0
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go mod download
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: latest

  docs_gen_diff:
    name: Generate and verify docs
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v5.5.0
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@97f030cf6dc0b4f5e0da352c7bca9cca34579800
        with:
          terraform_wrapper: false
      - run: go mod download
      - run: task gen
      - name: Generated docs git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v5.5.0
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go mod download
      - name: Build Check
        run: go build -v .

  unit_test:
    name: Unit Tests (race + coverage)
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v5.5.0
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go mod download
      - run: task test RACE=true COVER=true COVERPROFILE=coverage.out
      - name: Upload unit test coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage
          path: coverage.out
          if-no-files-found: warn
          retention-days: 7

  acceptance_test:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    needs: [unit_test]
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        terraform:
          - "1.7.*"
          - "1.8.*"
          - "1.9.*"
          - "1.10.*"
          - "1.11.*"
          - "1.12.*"
          - "1.13.*"
    steps:
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v5.5.0
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@97f030cf6dc0b4f5e0da352c7bca9cca34579800 # v3.1.0
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - run: go install gotest.tools/gotestsum@latest
      - run: go install github.com/bitfield/gotestdox/cmd/gotestdox@latest
      - env:
          JIRA_ENDPOINT: ${{ vars.JIRA_ENDPOINT }}
          JIRA_API_EMAIL: ${{ secrets.JIRA_API_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_TEST_ROLE_LEAD_ID: ${{ secrets.JIRA_PROJECT_TEST_ROLE_LEAD_ID }}
        run: task test ACC_ONLY=true
