# SPDX-License-Identifier: MPL-2.0
name: Release Drafter

on:
  push:
    # Trigger on all branches; restrict execution to the default branch at job-level.
    branches:
      - '**'
  pull_request:
    types: [opened, reopened, synchronize, edited, labeled, unlabeled, closed]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    # Run on PR events and manual dispatch; for push events, only on the repository default branch.
    if: ${{ github.event_name != 'push' || github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
